/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

/* Whether we can and want to do installation of missing plugins */
#define ENABLE_MISSING_PLUGIN_INSTALLATION

#define GETTEXT_PACKAGE "totem"

#undef GNOME_ENABLE_DEBUG

#define PACKAGE "totem"

#define TOTEM_API_VERSION "1.0"

#define VERSION "3.34.1"

